# SA Aspect Ratio Fixes v1.1.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-aspect-ratio-fixes

[general]
log=0
showReloadMessage=1
reloadHotkey=Alt+H

[radar]
roundRadar=1
roundBlips=1
# Only while roundRadar=1. Units of screen height, not pixels.
diameter=86
marginLeft=40
marginBottom=28

[crosshair]
roundCrosshair=1
roundScope=1
noCameraCrosshair=0
hideCameraHud=0
hideSniperHud=0

[widescreen]
useScreenAspect=0
# Does nothing while useScreenAspect=0.
fixFov=1

[worldSprites]
pickups=1
coronas=1
coronaReflections=1
sunMoon=1
pointLights=1
birds=1
clouds=1
checkpoints=1
weaponEffects=1
cameraEffects=1