# SA Aspect Ratio Fixes v1.0.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-aspect-ratio-fixes
# Default reload hotkey: Alt + H

[general]
log=0
hotkeyEnabled=1
hotkeyModifier=18
hotkeyKey=72
showNotifications=1

[radar]
enabled=1
roundRadar=1
roundBlips=1
diameter=76
marginLeft=40
marginBottom=28

[crosshair]
enabled=1
aspectMode=1
roundScope=1
noCameraCrosshair=0
hideCameraHud=0
hideSniperHud=0

[widescreen]
fixFov=1
useScreenAspect=1

[worldSprites]
pickups=1
coronas=1
coronaReflections=1
sunMoon=1
pointLights=1
birds=1
clouds=1
checkpoints=1
weaponEffects=1
cameraEffects=1
targetingMeasurements=0

[probe]
enabled=0
group=0
hotkeyModifier=18
hotkeyKey=80
